"""Per-city model blacklist loader.

Generated by scripts/generate_blacklist.py from 120-day backtest data.
"""

import json
import os

_BL_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, "data", "model_blacklist.json"))
_cache: dict | None = None


def _load():
    global _cache
    if _cache is not None:
        return _cache
    if not os.path.exists(_BL_PATH):
        _cache = {"model_blacklist": {}, "city_blacklist": []}
        return _cache
    with open(_BL_PATH) as f:
        _cache = json.load(f)
    return _cache


def get_blacklisted_models(city_code: str, metric: str = "temperature_max") -> set:
    """Return set of model names to exclude for this city+metric."""
    bl = _load().get("model_blacklist", {})
    raw = bl.get(city_code, [])
    out = set()
    for entry in raw:
        if entry.endswith("_min") and metric != "temperature_min":
            continue
        if entry.endswith("_min"):
            out.add(entry[:-4])  # strip _min suffix
        else:
            out.add(entry)
    return out
